apiVersion: backstage.io/v1alpha1
kind: API

metadata:
  name: demo-service-api-1
  description: Demo API
  
spec:
  type: openapi
  lifecycle: production
  owner: group:sre
  definition:
    $text: ./openapi.yaml
