apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-service-api
  description: Demo API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: ./openapi.yaml
