apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-service-api-1
  description: Demo API
annotations:
  accountIdentifier: 2KolbecvR0aAcgQ5uXBObA
  orgIdentifier: WiproPOC
  projectIdentifier: CSDemo
spec:
  type: openapi
  lifecycle: production
  owner: group:sre
  definition:
    $text: ./openapi.yaml
