apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demoservice
  description: .NET microservice
  annotations:
    github.com/project-slug: jagtappriyanka007/demoservice
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:platform-team
  lifecycle: production
  providesApis:
    - demoservice-api
