pipeline:
  name: Build demoservice
  identifier: Build_demoservice_1785995144699
  projectIdentifier: CSDemo
  orgIdentifier: WiproPOC
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Hello World
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Bash
                    command: |-
                      echo "This is my first demo"
                      echo "================================="
                      echo "       HARNESS CI DEMO"
                      echo "================================="
                      echo "Project Name : CSDemo"
                      echo "Pipeline Name: Build demoservice"
                      echo "Build Started Successfully"
                      echo "Current Date : $(date)"
                      echo "Current User : $(whoami)"
                      echo "Working Directory : $(pwd)"
                      echo "================================="
                      echo "Demo Completed Successfully"
                      echo "================================="
                  description: This my First Demo
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: demorepo
        repoName: demoservice
        build: <+input>
